<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAuM5QA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAuM5QA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAuM5QA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAuM5QA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAuM5QA\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAuM5QA',
    'container.build_id' => 'f676686d',
    'container.build_time' => 1605626336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAuM5QA');
